### ISSUE TITLE
Clean up dependencies and publish to NPM

### ISSUE THREAD

**Issue by MrLeebo** [coryhouse/switchboard#10]
The DevTool is hard to use/test as a component outside of the demo app currently:

- It's not published to NPM
- Maybe this is just my lack of familiarity with vite, but even if you build the npm package manually, it doesn't contain typescript definitions
- There are dependencies of the demo-app intermixed with the component's dependencies (react-router, tailwindcss, zod) so importing it creates conflicts with the app's versions of those dependencies

**Comment by coryhouse** [comment]
Agreed. I created a branch awhile back moving this to a monorepo setup https://github.com/coryhouse/switchboard/tree/build-lib. But haven't had a chance to finish it yet.
