### ISSUE TITLE
Enhanced Custom Response Editor

### ISSUE THREAD

**Issue by MrLeebo** [coryhouse/switchboard#11]
Currently, the custom response field is a tiny textbox that can't easily be edited for JSON responses.

It would be great to be able to swap that out for a dedicated JSON editor component. Or a Postman-style interface where you choose the response type and get a different editor based on your pick. There are several implementations of JSON editors for React, but I'm not familiar enough with them to make a specific library suggestion yet.

My dream feature would be to be able to pass in an API schema (for instance, a swagger/OpenAPI JSON doc) and the editor would automatically use the schema to detect the available http handlers and to validate the given response against the response schema for that endpoint.

That would be a pretty epic enhancement. As an easier stop-gap measure that wouldn't require as much coding, the DevTools component could accept a Response Editor prop to allow the app author to plug in their own custom component for editing the responses:

```ts
<DevTools
  {...devToolProps} 
  renderResponseEditor={(props, devToolState) => (
    <MyAwesomeJsonEditor value={props.value} onChange={props.onChange} schema={swaggerDoc} />
  )}
/>
```

**Comment by coryhouse** [comment]
I agree. My vision is to replace all 3 inputs with a dropdown of "custom responses". 

Advantages:
1. Quicker configuration
2. Lean URL (since it would only contain a customResponseId for a given endpoint
3. Eliminates the need to implement a custom JSON editor, or support someone bringing in their own

That said, I agree the idea of using an OpenAPI spec is compelling. Same with a GraphQL schema. 

Those are both roads worth pursuing, and perhaps even easier to do well than the array of "custom responses" for each endpoint. 

The issue with leaning solely on OpenAPI/GraphQL, is not everyone uses them. 

So perhaps a combination of all 4 approaches is warranted:
1. OpenAPI
2. GraphQL schema
3. Optional array of custom responses for each endpoint
4. Existing 3 inputs for total control

**Comment by MrLeebo** [comment]
I like your reasoning on this. I think it's worth it to have a straightforward path for adoption using an API schema (OpenAPI/GraphQL) because if you want to use Switchboard for Cypress tests and other cases where the custom responses are going to persist for a long time, you need a way to ensure the mocked response doesn't fall out of sync with the actual API. So the API schema is pulling double duty here by helping you set up your custom responses accurately and it should be able to alert you if it tries to load a custom response that doesn't sync with the schema anymore.

It makes sense for the input prop that the DevTools component receives to always be a list of MSW http handlers. Whether the handlers are generated from a schema doc, by hand, or hard-coded into the source code, they could always be converted into MSW handlers first, so the component doesn't really need to details about how each solution works.

```ts

/* Pass a prop containing MSW handlers directly */
const requestHandlers = [
  rest.get("/api/projects", (req, res, ctx) => ...)
]

/* Or convert a schema into handlers as an external function */
// const res = await fetch("/api/swagger.json")
// const docs = await res.json()
// const requestHandlers = generateHandlersFromSwaggerDocExamples(docs)

/* Or perhaps a combination of multiple sources */
// const requestHandlers = [
//   ...hardcodedHandlers,
//   ...swaggerHandlers,
//   ...userDefinedHandlers,
// ]

<DevTools {...devToolProps} httpSettings={{ requestHandlers }} />
```

That way the component itself isn't dealing with multiple different abstractions; it only has to think about MSW handlers.

Similarly, the storage mechanism for saving edited responses can probably also be abstracted out of the main component.

```ts
import * as stores from 'switchboard/stores'

/* Probably the default if unspecified, since it is self-contained, shareable, easy to grok */
const storage = new stores.SearchParamStore({ paramName: "customResponses" })

/* Switchboard can provide some alternative stores or keep them as separate packages */
// const storage = new stores.MemoryStore()
// const storage = new stores.HashStore({ paramName: "customResponses" })
// const storage = new stores.LocalStorageStore({ keyName: "customResponses" })
// const storage = new stores.IndexedDBStore({ tableName: "customResponses" })

/* Or the user can provide a custom store to save their responses in a DB table or something */
// const storage = {
//   onSaveResponse((response) => fetch("/api/switchboard", { method: "POST", body: ... })),
//   onLoadResponse((responseId) => fetch(`/api/switchboard/${responseId}`).then(...))
//   onGetResponseList(() => fetch("/api/switchboard").then(...))
// }

<DevTools {...devToolProps} storage={storage} />
```

**Comment by MrLeebo** [comment]
<img width="1238" alt="Screen Shot 2022-09-26 at 8 58 26 AM" src="https://user-images.githubusercontent.com/2754163/192363637-4ebbabd8-a0d2-4df5-8525-a8babaa05d84.png">

@coryhouse I started working on a "glow up" of the response editor, but I got side-tracked because I ended up needing to build more foundational components (like `<Tabs>`, `<Tooltip>`, `<Select>`, etc) to put it together. So it turned into a more general UI rework.

I'm trying to achieve these characteristics:

- Incorporates tabbed interfaces
  - As the number of options grows, a purely vertical layout will be hard to navigate
  - As you mentioned, switching between a full editor vs canned custom responses
- I'm also interested in allowing multiple instances of a handler to be assigned to the same endpoint:
  - They could have conditional triggers, like maybe the response delay is 0 normally, but if `:id  > 10` then it gets a 10 second delay, and `:id > 100` returns a 400 status code. So one endpoint with 3 handlers attached to it.
- Editable table for setting HTTP response headers
  - So within the Custom Response Form, there might be tabs for `Body / HTTP Headers / Conditional Triggers` etc 
- I think you would choose the API endpoint to edit first, then it drills down to the list of handlers you've created for that endpoint, then you have to choose the handler you want to edit.
  - That way the tool only has to render one response form at a time.

**Comment by coryhouse** [comment]
Hi Jeremy - Thanks for the thoughtful reply! I've been thinking about going a different direction and exposing this as a headless component. That way people can choose their UI. Or perhaps the UI provided could be a default that's easily replaced. Developers tend like to customize things, so I figure a headless option would help address that. 

That said, I've found headless components as a concept are confusing, so perhaps having a robust built in UI as an option remains important. Tough calls here. Still thinking on this.

**Comment by MrLeebo** [comment]
Yeah, a Headless component makes sense, especially if down the road you want to target other frameworks like vue and svelte.

I think having a strong default component is important too because a) the tool doesn't "demo" well if you can't see it in action, b) there are probably only a handful of aspects of the tool that the developer will seek to customize, they'll want to use the default component for the rest, and c) I can see a tool like this being a popular fixture in the demo apps of other component libraries, so a solid default component makes for good "branding" insofar as open source projects care about that.

Since I have started working on these changes already, should I incorporate factoring out a headless component into this branch, or do you have a headless branch started already that I should hold off for?

**Comment by coryhouse** [comment]
Yeah, I agree with all that. The headless component idea can wait. I see it as a phase 2. Thanks for the dialogue and your contributions!

**Comment by MrLeebo** [comment]
Closing this. The JSON editors I sampled tended to be fairly large dependencies, or had global impacts, like styling using .css files. And in practice I've found data profiles to be a much more desirable way of setting up mocks, so I don't think there's going to be much interest for a really fancy ad-hoc mock response editor.
